version: "3"

services:
  jenkins:
    build: ./jenkins
    image: cd_jenkins:latest
    container_name: jenkins
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
      - ./ansible:/ansible
  
  nexus:
    image: sonatype/nexus3:3.32.0
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - ./nexus-data:/nexus-data
    
  test_fixture:
    build: ./test_fixture
    image: test_fixture:latest
    container_name: test_fixture
    ports:
        - "8888:8888"
        - "2222:22"

networks: 
  default:
    external: true
    name: shared-backend