all:
  children:
    test_fixture:
      hosts:
        test_fixture:
      vars:
        ansible_connection: ssh
        ansible_port: 22
        ansible_user: root
        ansible_ssh_pass: P@ssW0rd!
